### PR TITLE
fix: optimized if-statement in configmap.yaml

### PR DESCRIPTION
**Pull request by Kerwood**
Turned this:
```
{{- if $config_lookup -}}
  {{- if $config_lookup.data -}}
    {{- if $config_lookup.data.state_key -}}
      {{- $config = $config_lookup.data.state_key -}}
```
Into this:
```
  {{- if (($config_lookup).data).state_key -}}
  {{- $config = $config_lookup.data.state_key -}}
```

### CODE REVIEW

**Review by yairsimantov20 — APPROVED** [review]
🌊 Looking good

**Comment by Kerwood** [comment]
Rebased and fixed conflicts.

**Comment by yairsimantov20** [comment]
Can you please also bump the version in the chart.yaml
It is still managed manually

**Comment by Kerwood** [comment]
Done

**Pull request merged**
